# config.yaml
library: "gradcam"              # Library for generating explanations
method: "GradCAM"               # Explanation method to use
model_names:                    # List of models to use
  # - "alexnet"
  - "resnet50"
  # - "swin_transformer"
  # - "vit"
perturbation_names:             # List of perturbation methods to use
  - "Gaussian"
  - "Blur"
  - "Occlusion"
  - "Void"
  - "InvGrad" 
sample_images: 5                # Number of sample images to process, -1 for all
n_perturbations: 10             # Number of perturbed images to generate for analysis
magnitude: 0.1                  # Maximum noise magnitude for generating perturbed images
seed: 24                        # Random seed for reproducibility
